import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../modules/shared/components/Navbar";
import Footer from "../modules/shared/components/Footer";
import { AuthProvider } from "@/modules/auth/contexts/authContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Matribhasha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <AuthProvider>
          <Navbar></Navbar>
          <main className="h-full">
            {children}
          </main>
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
